cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [

    path('add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('add/', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update/', views.update_cart, name='update_cart'),
    path('remove-product/', views.remove_product, name='remove_product'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('', include('pages.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order-create/', views.order_create_view, name='order_create'),
    path('user_orders/', views.UserOrdersList.as_view(), name='user_orders'),
]

products/urls.py
from django.urls import path

from . import views


app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products/', views.ProductListView.as_view(), name='products_list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/<int:product_id>/', views.CommentCreateView.as_view(), name='create_comment')

]

cart/views.py
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST
from django.http import JsonResponse

from products.models import Product
from products.serializers import ProductSerializer
from .cart import Cart


@require_POST
def add_to_cart(request, product_id=None):


    if product_id is None:
        product_id = request.POST.get('item_id')

    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)

        cart.add(product)
        products = Product.objects.filter(id__in=request.session['cart'])
        cart_ser = ProductSerializer(products, many=True)


        context = {
            'cart_ser': cart_ser.data,
            'item_count': len(cart),
            'cart_total_price': cart.get_total_price()
        }
    
        return JsonResponse(context)

    except:
        return JsonResponse(status=400, data={'error': 'invalid request'})


def cart_detail(request):
    cart = Cart(request)

    context = {
        'cart': cart,
    }
    return render(request, 'cart/cart_detail.html', context)


@require_POST
def update_cart(request):
    item_id = request.POST.get('item_id')
    action = request.POST.get('action')

    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)

        if action == 'add':
            cart.add(product)
        
        else:
            cart.reduce(product)

        context = {
            'item_count': len(cart),
            'cart_total_price': cart.get_total_price(),
            'quantity': cart.cart[item_id]['quantity'],
            'total_price_product': cart.cart[item_id]['price'] * cart.cart[item_id]['quantity'],
            'final_price': cart.get_total_price(),
            'success': True,
        }        

        return JsonResponse(context)
    except:
        return JsonResponse(status=404, data={'sucess': False, 'error': 'item not found'})


@require_POST
def remove_product(request):
    item_id = request.POST.get('item_id')


    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)
        cart.remove(product)
        products = Product.objects.filter(id__in=request.session['cart'])
        cart_ser = ProductSerializer(products, many=True)

        context = {
            'cart_ser': cart_ser.data,
            'item_count': len(cart),
            'cart_total_price': cart.get_total_price(),
            'final_price': cart.get_total_price(),
            'success': True,
        }

        return JsonResponse(context)
    except:
        return JsonResponse(status=404, data={'sucess': False, 'error': 'item not found'})

cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}سبد خرید{% endblock %}

{% block body %}
{% block header %}
{% endblock %}

    <main>
    
        <section>
            
            <div class="w-[97%] xs:w-[94%] mb-4 rounded-md container mt-5 md:mt-36 md:mb-11 bg-white dark:bg-zinc-700 text-zinc-700 dark:text-white shadow-normal xs:rounded-xl">
                <div class="flex justify-between font-DanaMedium pt-8">
        
                    <div class="text-xl sm:text-3xl pr-4 dark:text-white">
                        <h2>سبد خرید</h2>
                    </div>
        
                    <div class="inline-block pl-4">
                        {% with item_count=cart|length %}
                         <span>تعداد <span class="cart-count dark:text-white"> {{ item_count }}</span></span>
                        {% endwith %}
                    </div>
                </div>
        
                <div class="sm:px-4">
                    <div class="grid grid-cols-1">
                        {% if cart %}
                        {% for item in cart %}
                        <div class="product-item flex justify-between items-center shrink gap-x-4 border-t border-t-gray-300 mt-3 pt-5" data-item-id="{{ item.product_obj.id }}">
                            <div>
                            
                                <img src="{{ item.product_obj.image.url }}" class="w-[80px] xs:w-[100px] sm:w-[120px] lg:w-[140px]">
                            </div>
        
                            <div class="text-xs xs:text-sm md:text-xl font-DanaMedium line-clamp-1">
                                <a href="{{ item.product_obj.get_absolute_url }}">{{ item.product_obj.title }}</a>
                            </div>
        
                            <div class="actions">
                
                                    <input type="submit" value="+" class="quantity-add w-5 hover:cursor-pointer">
                                    <span id="quantity-{{ item.product_obj.id }}">{{ item.quantity }}</span>
                                    <input type="submit" value="-" class="quantity-reduce w-5 hover:cursor-pointer">
                              
                            </div>
        
                            <div class="text-xs xs:text-sm md:text-xl font-DanaMedium">
                                <span id="total-price-product-{{ item.product_obj.id }}">{{ item.total_price|intcomma:False }}</span>
                            </div>
        
                            <div>

                                    <div>
                                        <svg class="product-remove w-5 h-5 sm:w-6 sm:h-6 text-red-500">
                                            <use href="#trash"></use>
                                        </svg>
                                    </div>

                            </div>
                        </div>
                        {% endfor %}
                     
                        {% endif %}
        
                        
                        
                    </div>
                </div>

            
                    <div id="full-cart" class="{% if not cart %}hidden{% endif %}">

                        <div class="pb-3 pt-3 sm:px-4">
                
                            <div class="mt-5 sm:mt-2 border-t border-gray-300">
                                <div class="pb-3 mt-4.5 sm:mt-8 flex justify-between">
                                    <div>
                                        <span class="sm:text-xl">مبلغ قابل پرداخت :<span class="sm:font-DanaDemiBold">{{ cart.get_total_price|intcomma:False }}</span> تومان</span>
                                    </div>
                    
                                    <div class="hover:underline text-sm sm:text-lg">
                                        <a href="{% url 'products:home' %}">بازگشت به فروشگاه</a>
                                    </div>
                                </div>
                    
                            </div>
                        </div>
        
                            <div class="flex justify-center">
                                <div class="text-zinc-700 sm:mr-4 w-full sm:mb-4">
                                    <a href="{% url 'orders:order_create' %}" class="inline-block text-center w-full text-sm lg:text-xl sm:w-[200px] mb-5 bg-orange-300 px-5 py-3 lg:py-4 rounded-full">ثبت سفارش</a>
                                </div>
        
                            </div>
                    </div>



                
                <div id="empty-cart" class="{% if cart %}hidden{% endif %} container"> 

                    <div class="flex justify-between items-center">
    
                        <div class="mt-8 mb-7">
                            <span class="text-zinc-700 dark:text-white">سبد خرید شما خالی است.</span>
                        </div>
                        <div class="hover:underline text-sm sm:text-lg">
                            <a href="{% url 'products:home' %}">بازگشت به فروشگاه</a>
                        </div>
                    </div>
                </div>

            </div>
        


        </section>
</main>
{% block script %}
<script>
    $(document).ready(function(){

        $('.quantity-add').on('click', function(){
            updateQuantity($(this).closest('.product-item').data('item-id'), 'add');
        }); 
    
        $('.quantity-reduce').on('click', function(){
             updateQuantity($(this).closest('.product-item').data('item-id'), 'reduce');
         });

          $('.product-remove').on('click', function(){
             removeProduct($(this).closest('.product-item').data('item-id'));
         });
        
        function updateQuantity(itemId, action){
            $.ajax({
                type: 'POST',
                url: '{% url "cart:update_cart" %}',
                data: {
                    'item_id': itemId,
                    'action': action,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response){
                    if(response.success){
                        $('.cart-count').text(response.item_count);
                        $('#cart-total-price').text(response.cart_total_price);
                        $('#quantity-' + itemId).text(response.quantity);
                        $('#total-price-product-' + itemId).text(response.total_price_product);
                        $('#final-price').text(response.final_price);
                    } else {
                        alert('error updating quantity');
                    }
                }
            });
        }

                function removeProduct(itemId){
            $.ajax({
                type: 'POST',
                url: '{% url "cart:remove_product" %}',
                data: {
                    'item_id': itemId,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response){
                    if(response.success){
                        $('.cart-count').text(response.item_count);
                        $('#cart-count').text(response.cart_count);
                        $('#cart-total-price').text(response.cart_total_price);
                        $('#final-price').text(response.final_price);
                        $(`.product-item[data-item-id=${itemId}]`).remove();
                        $('empty-cart').remove();
                        cartBoxRefresh(response, {
                            cart_detail: "{% url 'cart:cart_detail' %}", 
                            order_create: "{% url 'orders:order_create' %}"});
                        if(response.item_count == 0){
                            $('#empty-cart').removeClass('hidden');
                            $('#full-cart').addClass('hidden');
                        }
                    } else {
                        alert('error remove product');
                    }
                }
            });
        }


    });
</script>
{% endblock %}
{% endblock %}