accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('account_activation_sent/', views.AccountActivationSentView.as_view(), name='account_activation_sent'),
    path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),
    path('account_activation_complete/', views.AccountActivationComplete.as_view(), name='account_activation_complete'),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('account-info/', views.AccountInfoView.as_view(), name='account_info'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [

    path('add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('add/', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update/', views.update_cart, name='update_cart'),
    path('remove-product/', views.remove_product, name='remove_product'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('', include('pages.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order-create/', views.order_create_view, name='order_create'),
    path('user_orders/', views.UserOrdersList.as_view(), name='user_orders'),
]

products/urls.py
from django.urls import path

from . import views


app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products/', views.ProductListView.as_view(), name='products_list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/<int:product_id>/', views.CommentCreateView.as_view(), name='create_comment')

]

orders/models.py
from django.db import models
from django.conf import settings

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, verbose_name='نام گیرنده')
    last_name = models.CharField(max_length=100, verbose_name='نام خانوادگی گیرنده')
    phone_number = models.CharField(max_length=15, verbose_name='شماره تلفن')
    province = models.CharField(max_length=100, verbose_name='استان')
    city = models.CharField(max_length=100, verbose_name='شهر')
    address = models.CharField(max_length=700, blank=True)
    postal_code = models.CharField(max_length=20, verbose_name='کدپستی')
    is_paid = models.BooleanField(default=False)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)
    zarinpal_authority = models.CharField(max_length=255, blank=True)
    zarinpal_ref_id = models.CharField(max_length=150, blank=True)
    zarinpal_data = models.TextField(blank=True)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_price(self):
        # result = 0
        # for item in self.items.all():
        #     result += item.price * item.quantity

        return sum(item.price * item.quantity for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE, related_name='order_items')
    quantity = models.PositiveIntegerField(default=1)
    price = models.PositiveIntegerField()

    def __str__(self):
        return f'OrderItem {self.id} of {self.order.id}'

orders/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'province', 'city', 'address', 'postal_code', 'phone_number',]

orders/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Prefetch
from cart.cart import Cart
from .forms import OrderForm
from .models import OrderItem, Order


@login_required
def order_create_view(request):
    order_form = OrderForm()
    cart = Cart(request)

    if len(cart) == 0:
        messages.warning(request, 'سبد خرید شما خالی است، لطفا محصولی را به سبد خرید اضافه کنید.')
        return redirect('products:products_list')

    if request.method == 'POST':
        order_form = OrderForm(request.POST)

        if order_form.is_valid():
            order_object = order_form.save(commit=False)
            order_object.user = request.user
            order_object.save()

            for item in cart:
                product = item['product_obj']
                OrderItem.objects.create(
                    order=order_object,
                    product=product,
                    quantity=item['quantity'],
                    price=product.price,
                )

            cart.clear()

            request.session['order_id'] = order_object.id
            return redirect('payment:payment_process')

    return render(request, 'orders/order_create.html', {'form': order_form})


class UserOrdersList(LoginRequiredMixin,ListView):
    template_name = 'orders/user_orders.html'
    context_object_name = 'orders'
    paginate_by = 3
    
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)\
        .prefetch_related(Prefetch(
            'items',
             queryset=OrderItem.objects.select_related('product'))).all()\
        .order_by('-datetime_created')

orders/templates/orders/order_create.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block title %}سبد خرید{% endblock %}

{% block body %}
{% block header %}
{% endblock %}
<div class="container mb-8 mt-5 md:mt-40 flex flex-col lg:flex-row justify-center items-start md:gap-x-5">
    <div
        class="flex flex-col w-full lg:w-2/5 lg:h-[400px] max-lg:max-h-[450px] p-2 mb-5 shadow-normal bg-white dark:bg-zinc-700/[.8] text-zinc-700 dark:text-white rounded-xl ">

        <div class="flex justify-center pt-3 text-zinc-700 dark:text-white">
            <div>

                <span class="text-orange-300 font-DanaMedium md:text-xl">خلاصه سفارش</span>
            </div>

        </div>
        <div
            class="flex-1 overflow-y-scroll 
            [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-track]:m-1.5 [&::-webkit-scrollbar-track]:rounded-xl [&::-webkit-scrollbar-thumb]:bg-gray-700 [&::-webkit-scrollbar-thumb]:rounded-xl">
            {% for item in cart %}
            <div class="flex justify-between items-center px-3 mb-2 ">
                <div>
                    <img src="{{ item.product_obj.image.url }}" class="w-24 md:w-28 [mix-blend-mode: color]" alt="">
                </div>
                <div class="line-clamp-1">
                    <span>{{ item.product_obj.title }}<span>
                </div>
                <div>
                    <span>x{{ item.quantity }}</span>
                </div>
            </div>
            {% endfor %}
        </div>
        <div
            class="flex justify-between mb-5 mx-3 pt-4 md:text-xl border-t-2 border-t-gray-300 text-zinc-700 dark:text-white">
            <div>
                <span>قیمت کل:</span>
            </div>
            <div>
                <span>{{ cart.get_total_price|intcomma:False }} تومان</span>
            </div>
        </div>

    </div>

    <div
        class="w-full lg:w-3/5 md:h-[400px] lg:mb-16 pb-5 pt-3 shadow-normal rounded-xl bg-white dark:bg-zinc-700/[.8] text-zinc-700 dark:text-white">
        <div class="text-center pt-3">
            <h3 class="font-DanaMedium text-orange-300 md:text-xl">ثبت سفارش</h3>
        </div>
        <div>

            <form method="post" action="">
                {% csrf_token %}
                <div class="grid grid-cols-1 md:grid-cols-2 child:mt-2 px-5 md:child:mt-1 md:gap-x-4 md:p-4">



                    <div class="order-input child:inline-block child:w-full">

                        <input name="first_name" type="text" class="bg-gray-100 dark:bg-zinc-600" id="first-name"
                            placeholder="نام گیرنده">
                    </div>
                    <div class="order-input child:inline-block child:w-full">

                        <input name="last_name" type="text" class="bg-gray-100 dark:bg-zinc-600" id="last-name"
                            placeholder="نام خانوادگی گیرنده">
                    </div>

                    <div class="order-input child:inline-block child:w-full">

                        <input name="phone_number" type="text" class="bg-gray-100 dark:bg-zinc-600" id="phone-num"
                            placeholder="شماره تلفن">
                    </div>
                    <div class="order-input child:inline-block child:w-full">

                        <input name="province" type="text" class="bg-gray-100 dark:bg-zinc-600" id="province"
                            placeholder="استان">
                    </div>

                    <div class="order-input child:inline-block child:w-full">

                        <input name="city" type="text" class="bg-gray-100 dark:bg-zinc-600" id="city" placeholder="شهر">
                    </div>

                    <div class="order-input child:inline-block child:w-full">

                        <input name="postal_code" type="text" class="bg-gray-100 dark:bg-zinc-600" id="postal-code"
                            placeholder="کد پستی">
                    </div>
                    <div class="order-input child:inline-block child:w-full">

                        <textarea name="address" id="address" placeholder="ادامه آدرس" cols="30" rows="3"
                            class="bg-gray-100 dark:bg-zinc-600"></textarea>

                    </div>

                </div>

                <div class="flex justify-center">
                 <input type="submit" value="پرداخت"
                        class="inline-block bg-orange-300 p-2 w-1/2 text-zinc-700 text-center mt-2.5 md:mt-0 rounded-full hover:cursor-pointer">

                </div>
            </form>
        </div>
        <div>

        </div>



    </div>

</div>
{% endblock %}

orders/templates/orders/user_orders.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block title %}سفارشات{% endblock %}

{% block body %}
{% block header %}
{% endblock %}
<section class="container mb-10 md:mt-32 text-zinc-700 dark:text-white">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-x-4 mb-5">
            <div class="text-center h-fit mt-9 p-4 px-0 [&>*:first-child]:mt-0 child:rounded-md [&>*:hover]:bg-orange-300 [&>*:hover]:dark:text-zinc-700 child:dark:text-white child:p-3 child:mt-5 child:block child:hover:cursor-pointer child:text-zinc-700">

            
                <a href="{% url 'orders:user_orders' %}" class="mt-0">تاریخچه سفارشات</a>
                
                <a href="{% url 'accounts:account_info' %}">اطلاعات کاربری</a>

                <a href="{% url 'accounts:password_change' %}">تغییر رمز عبور </a>
        
                <a href="{% url 'products:products_list' %}">فروشگاه</a>

                <form method="post" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <input type="submit" value="خروج" class="hover:cursor-pointer">
                </form>
  
             
            </div>
            <div class="md:col-span-3 p-3 md:pr-6 mt-6 space-y-2 md:border-r border-gray-300">
                <span class="text-xl">سفارشات</span>
                {% for order in orders %}
                <div>
                    <div class="flex gap-x-3 mt-4 pt-3 mb-2.5 border-t border-b-gray-300">
                        <svg class="w-5 h-5">
                            <use href="#tick"></use>
                        </svg>
                        <span>پرداخت شده</span>
                    </div>
                    
                <div class="flex gap-x-5">
     
                    <p>{{ order.datatime_created }}</p>
                    <p class="text-xs text-neutral-400">کد سفارش <span class="text-zinc-700 dark:text-white text-base">{{ order.zarinpal_ref_id }}</span></p>
                    <p class="text-xs text-neutral-400">مبلغ <span class="text-zinc-700 dark:text-white text-base">{{ order.get_total_price|intcomma:False }}</span></p>
                </div>
               
                   
          
                    <div class="flex overflow-x-scroll gap-x-2 mt-3">
                        {% for item in order.items.all %}
                        <img class="w-[100px] h-[100px]" src="{{ item.product.image.url }}" alt="">
                        {% endfor %}
                    </div>
                 
                {% endfor %}
                </div>

            </div>
    
        </div>

    </section>
    
    {% include 'pagination.html' %}
{% endblock %}