cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [

    path('add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('add/', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update/', views.update_cart, name='update_cart'),
    path('remove-product/', views.remove_product, name='remove_product'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('', include('pages.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('contact-us/', views.ContactUsView.as_view(), name='contact_us'),
    path('contact/comment/', views.ContactUsCreateView.as_view(), name='contact_comment'),
]

pages/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}درباره ما{% endblock %}

{% block body %}


<main>
        
  <div>
      <img src="images/about.jpg" alt="" class="w-full">
  </div>

  <div class="flex justify-center text-zinc-700 dark:text-white mb-24">

      <div class="text-center w-[730px] mt-20">
          <h3 class="md:text-xl">داستان ما از کجا شروع شد؟</h3>
          <span class="inline-block mt-4 text-orange-400">از تیمی سه نفره تا خانواده‌‌ای 200 نفره</span>
          <p class="md:text-lg/8 mt-5 text-justify px-5 md:px-0">
              داستان قهوه هزار و یک شب داستان رشد بذر قهوه است؛ همان بذری که از دل خاک جوانه زد و در تمامی این سال‌ها با ذوق زیر نور خورشید نشست تا قدش بلند و بلندتر شود. بذر ما در یکی از روزهای گرم اولین ماه تابستان کاشته شد و ریشه آن هر روز در خاک محکم‌تر شد تا درخت آن به ثمر بنشیند. سال‌های زیادی گذشت، ما در کنار شما رشد کردیم و علاقه مشترک‌مان یعنی قهوه، انگیزه گفت‌وگوهای بسیار و دست یافتن به یک ماموریت واضح و مشخص شد: خلق تجربه‌ای یکتا از نوشیدن قهوه‌ای تازه برشت و باکیفیت.
          </p>
      </div>
  </div>

  <div class="text-center text-zinc-700 dark:text-white mb-11">
      <h4 class="font-DanaMedium text-xl">ویژگی های کافه هزار و یک شب</h4>

      <div class="flex flex-wrap gap-x-11 md:gap-x-28 justify-center">
         
          <div class="mt-8">
              <span class="inline-block mb-3 md:text-xl">تنوع و تازگی</span>
              <svg class="w-24 h-24 md:w-40 md:h-40">
                  <use href="#coffee-beans"></use>
              </svg>

          </div>
          <div class="mt-8">
              <span class="inline-block mb-3 md:text-xl">تعهد کیفیت بالا</span>
              <svg class="w-24 h-24 md:w-40 md:h-40">
                  <use href="#coffee-tree"></use>
              </svg>

          </div>
          <div class="mt-8">
              <span class="inline-block mb-3 md:text-xl">مشاوره هوشمند و رایگان</span>
              <svg class="w-24 h-24 md:w-40 md:h-40">
                  <use href="#coffee-cup"></use>
              </svg>
          </div>
      </div>
  </div>

  <div class="flex justify-center text-zinc-700 mb-20">
      <a href="{% url 'pages:contact_us' %}" class="bg-orange-300 px-5 py-2.5 rounded-full text-center">تماس با ما</a>
  </div>


</main>

{% endblock %}

pages/templates/pages/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% block title %}درباره ما{% endblock %}

{% block body %}


<main>
        
  <div class="container text-zinc-700 dark:text-white md:mt-36 mb-14">
      
   

      <div class="flex justify-center">

          <div class="mt-10 md:mt-[26px] max-w-[700px]">
              <h3 class="font-DanaDemiBold text-2xl mb-6 md:mb-7">فرم تماس با ما</h3>
              <div>
                  <form method="post" action="{% url 'pages:contact_comment' %}" class="child:outline-none child:w-full">
                    {% csrf_token %}
                      <input name="full_name" class="p-3 mt-3 dark:bg-zinc-600" type="text" placeholder="نام و نام خانوادگی">
                      <input name="phone_number" class="p-3 mt-3 dark:bg-zinc-600" type="text" placeholder="تلفن تماس">
                      <input  name="title" class="p-3 mt-3 dark:bg-zinc-600" type="text" placeholder="موضوع پیام">
                      <textarea name="content" class="p-3 mt-3 dark:bg-zinc-600" name="" id="" cols="30" rows="3" placeholder="متن پیام خود را بنویسید"></textarea>
                      <div class="flex justify-center md:mt-4">

                          <input type="submit" value="ارسال" class="md:text-xl text-zinc-700 bg-orange-300 p-3 rounded-full w-full md:w-[200px] hover:cursor-pointer">
                      </div>
                  </form>

              </div>
          </div>
      </div>
      <div class="">

          <div class="mt-10 md:mt-[26px]">
                  <h4 class="font-DanaDemiBold text-2xl mb-6 md:mb-7">در تماس باشیم</h4>
                  <div>
                      <div class="text-xl mb-6 md:mb-10">
                          <span class="flex items-center gap-x-2 md:gap-x-3 mb-4 md:mb-5">
                              <svg class="shrink-0 w-5 h-5 md:w-6 md:h-6">
                                  <use href="#map-pin"></use>
                              </svg>
                              بلوار میرداماد، خیابان البرز، کوچه قبادیان شرقی، پلاک ۳۳
                          </span>
  
                          <div class="flex flex-wrap gap-x-5 gap-y-4 font-DanaMedium">
                              <a href="#" class="flex items-center gap-x-2 md:gap-x-3">
                                  <svg class="w-5 h-5 md:w-6 md:h-6">
                                      <use href="#envelope"></use>
                                      
                                  </svg>
                                  info@coffee.com
                              </a>
                              <div class="flex items-center gap-x-3 md:gap-x-4">
                                  <svg class="w-5 h-5 md:w-6 md:h-6">
                                      <use href="#phone-contact-us"></use>
                                      
                                  </svg>
                                  <span class="ltr-text">0902 123 6628</span>
                                  <span class="ltr-text">021 - 6798012</span>
                              </div>
                          </div>
                      </div>
                      
                  </div>
              </div>
      </div>
    
     
  </div>

</main>

{% endblock %}