accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('account_activation_sent/', views.AccountActivationSentView.as_view(), name='account_activation_sent'),
    path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),
    path('account_activation_complete/', views.AccountActivationComplete.as_view(), name='account_activation_complete'),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('account-info/', views.AccountInfoView.as_view(), name='account_info'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [

    path('add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('add/', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update/', views.update_cart, name='update_cart'),
    path('remove-product/', views.remove_product, name='remove_product'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('', include('pages.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order-create/', views.order_create_view, name='order_create'),
    path('user_orders/', views.UserOrdersList.as_view(), name='user_orders'),
]

products/urls.py
from django.urls import path

from . import views


app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products/', views.ProductListView.as_view(), name='products_list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/<int:product_id>/', views.CommentCreateView.as_view(), name='create_comment')

]

products/models.py
from django.db import models
from django.shortcuts import reverse
from django_jalali.db import models as jmodels
from django.contrib.auth import get_user_model

from ckeditor.fields import RichTextField


class Product(models.Model):
    title = models.CharField(max_length=500)
    description = RichTextField()
    price = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='product/product_images')
    species = models.CharField(max_length=250)
    caffeine_amount = models.CharField(max_length=250)
    origin = models.CharField(max_length=250)
    ingredient = models.CharField(max_length=250)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    active = models.BooleanField(default=True)
    datetime_created = jmodels.jDateTimeField(auto_now_add=True)
    datetime_modified = jmodels.jDateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.pk])


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.user.first_name + ':' + self.product.title

products/forms.py
from django import forms

from .models import Comment


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body', ]

products/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Product, Comment
from .forms import CreateCommentForm


class HomeView(ListView):
    queryset = Product.objects.filter(active=True)[:4]
    template_name = 'home.html'
    context_object_name = 'products'

class ProductListView(ListView):
    queryset = Product.objects.filter(active=True)
    template_name = 'products/products.html'
    context_object_name = 'products'
    paginate_by = 8


class ProductDetailView(DetailView):
    queryset = Product.objects.prefetch_related('comments').all()
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CreateCommentForm()
        return context


class CommentCreateView(LoginRequiredMixin, CreateView):
    http_method_names = ['post']
    login_url = 'accounts:login'
    model = Comment
    form_class = CreateCommentForm

    def get_success_url(self):
        product_id = int(self.kwargs['product_id'])
        return reverse('products:product_detail', args=[product_id])

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        product_id = int(self.kwargs['product_id'])
        product = get_object_or_404(Product, id=product_id)
        obj.product = product
        return super().form_valid(form)

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load jformat %}
{% block title %}{{ product.title }}{% endblock %}

{% block body %}
{% block header %}
{% endblock %}
<main>
 

    <section class="products pt-8 md:pt-24 lg:pt-40 pb-20">
        <h2 class="font-MorabbaMedium hidden sm:block text-center mb-5 md:mt-14 lg:mt-0 text-zinc-700 dark:text-white text-4xl">{{ product.title }}</h2>
        <div class="container">
            <div>
                <p class="mb-2 hidden md:block text-zinc-700 dark:text-white">دسته بندی: دانه اسپرسو</p>
            </div>

            <div class="md:grid md:grid-cols-3 gap-x-11 md:gap-x-8">
                
                
                <div class="flex justify-center md:justify-between">
                    <div class="flex items-center bg-white dark:bg-zinc-700 w-[400px] rounded-2xl">
                        
                        <img src="{{ product.image.url }}" alt="coffee" class="w-96 dark:text-zinc-700 rounded-2xl">
                    </div>
                   
                </div>
                  <!-- title mobile -->
            <div class="block md:hidden">

                <h3 class="font-MorabbaMedium text-right mt-12 pb-2 text-zinc-700 dark:text-white text-2xl border-b border-b-gray-400 dark:border-b-white/10">دانه قهوه اسپرسو آرنیکا</h3>
                <div>
                    <p class="mt-2.5 text-zinc-700 dark:text-white">دسته بندی : دانه اسپرسو</p>
                </div>
            </div>
                <div class="product-attribute md:child:inline-block my-10 md:my-0">
                    <span class="inline-block mb-8 md:mb-0">ویژگی های محصول :</span>
                    <div class="inline-block">
                        <span class="inline-block px019">گونه : {{ product.species }}</span>
                    </div>
                    <div>
                        <span>میزان کافئین  : {{ product.caffeine_amount }}</span>
                    </div>
                    <div>
                        <span> خاستگاه : {{ product.origin }} </span>
                    </div>
                    <div>
                        <span>مواد تشکیل دهنده :  {{ product.ingredient }}</span>
                    </div>
                    <div>
                        <span>  وزن :  {{ product.weight|floatformat:0 }} گرم</span>
                    </div>
                    <div class="hidden md:block w-full text-center">
                        <div class="dark:text-white text-zinc-700 text-xl mb-1 font-DanaMedium flex justify-start">

                            <span class="">{{ product.price|intcomma:False }}<span class="font-Morabba">تومان</span></span>
                        </div>
             
                        
                            <div class="add-to-cart hover:cursor-pointer text-zinc-700 bg-orange-300 p-3 rounded-2xl">
                              
                                <input class="" type="submit" value="افزودن به سبد خرید">
                            </div>
                        
                    </div>

                </div>

                <div class="col-span-2 md:col-span-1">
                    <div class="inline-flex gap-x-3 items-center w-full p-4 mt-3 bg-white dark:bg-zinc-700 rounded-2xl">
                        <div class="rounded-full p-1 bg-gray-100 dark:bg-zinc-800">
                            <svg class="w-6 h-6 text-orange-300">
                                <use href="#truck"></use>
                            </svg>
                        </div>
                        <p class="text-xs md:text-sm/6 text-zinc-700 text-justify dark:text-white">کلیه سفارشات شهرستان که بعد از تاریخ ۲۰ اسفندماه ثبت شوند، از تاریخ 14 فروردین‌ماه تحویل شرکت پست خواهند شد.</p>
                    </div>
                    <div class="inline-flex gap-x-3 items-center w-full p-4 mt-3 bg-white dark:bg-zinc-700 rounded-2xl">
                        <div class="rounded-full p-1 bg-gray-100 dark:bg-zinc-800">
                            <svg class="w-6 h-6 md:w-6 md:h-6 text-orange-300">
                                <use href="#guarantee"></use>
                            </svg>
                        </div>
                        <p class="text-xs md:text-sm/6 text-zinc-700 text-justify dark:text-white">7 روز ضمانت بازگشت کالا</p>
                    </div>
                    <div class="inline-flex gap-x-3 items-center w-full p-4 mt-3 bg-white dark:bg-zinc-700 rounded-2xl">
                        <div class="rounded-full p-1 bg-gray-100 dark:bg-zinc-800">
                            <svg class="w-5 h-5 text-orange-300">
                                <use href="#support"></use>
                            </svg>
                        </div>
                        <p class="text-xs md:text-sm/6 text-zinc-700 text-justify dark:text-white">پشتیبانی سریع</p>
                    </div>
    
                </div>
                 
                
            </div>


          
          



            <div class="text-zinc-700 dark:text-white mt-10 mb-6 text-justify">
                <h4 class="font-DanaMedium mb-3 text-orange-300 text-xl md:text-2xl">معرفی محصول</h4>
                <div  class="text-lg md:text-xl md:leading-10">

                    <p>
                       {{ product.description | safe }}
                    </p>
                </div>
            </div>

                        <div>
                            <span class="font-DanaDemiBold text-orange-300">ایجاد نظر جدید</span>
                            {% if user.is_authenticated %}
                            <form method="post" action="{% url 'products:create_comment' product.id %}">
                                {% csrf_token %}
                                <div class="mt-4">
                                    <textarea name="body" class="w-full block dark:bg-zinc-600 dark:text-white font-DanaMedium text-sm outline-none p-4.5 md:p-4 md:w-1/2 rounded-2xl" name="" id="" cols="30" rows="6" placeholder="نظر خود را بنویسید ..."></textarea>
                                </div>
                                <div class="flex font-DanaMedium justify-center mt-4.5 sm:mt-6 rounded-lg text-zinc-700 h-[48px] cursor-pointer w-[144px] bg-orange-300">
                                    <input type="submit" value="ارسال">
                                </div>
                            </form>
                            {% else %}
                             <div class="text-zinc-700 dark:text-white mt-5">
                                <span>برای ثبت نظر باید ابتدا <a href="{% url 'accounts:login' %}" class="text-orange-300">وارد</a> شوید.</span>
                             </div>
                            {% endif %}

                        </div>
                        
                        <div class="mt-11 border p-3 border-gray-400 dark:border-zinc-700">

                            <div>
                                <span class="dark:text-white font-MorabbaMedium text-xl">نظرات</span>
                            </div>
                            {% if product.comments.all %}
                            {% for comment in product.comments.all %}
                            <div class="mt-3 bg-white dark:text-white dark:bg-zinc-700 p-3 rounded-md">
                                <p>{{ user.username }}</p>
                                <span>{{ comment.datetime_created|jformat:"%d / %m / %Y - %H:%M" }}</span>
                                <div class="mt-3 border-t border-gray-200 dark:border-zinc-600">
                                    <p class="mt-3">
                                        {{ comment.body }}
                                    </p>
                                </div>
                            </div>
                            {% endfor %}
                            {% else %}
                            <div class="mt-5">
                                <span class="text-zinc-700 dark:text-white">نظری برای این محصول وجود ندارد</span>
                            </div>
                            {% endif %}
                          
                        </div>
        
        </div>


              <!-- mobile add to cart -->
              <div class="fixed bottom-0 md:hidden text-whit bg-orange-300 w-full h-[70px] z-10">
                <div class="flex justify-between items-center py-3 px-5">
            
                        
                        <div class="add-to-cart cursor-pointer text-zinc-700 bg-white p-3 rounded-2xl">
                            <input class="" type="submit" value="افزودن به سبد خرید">
                        </div>
          

                    <div>
                        <span class="text-zinc-700 font-DanaDemiBold"> {{ product.price|intcomma:False }}تومان</span>
                    </div>
                </div>
            </div>
                
            


    </section>
</main>

{% block script %}
<script>
    $(document).ready(function(){
        $('.add-to-cart').click(function(){

            $.ajax({
                type: 'POST',
                url: "{% url 'cart:add_to_cart' product.id %}",
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    $('.cart-count').text(data.item_count);
                    cartBoxRefresh(data, {
                            cart_detail: "{% url 'cart:cart_detail' %}", 
                            order_create: "{% url 'orders:order_create' %}"});
                    
                },
            });
        });
    });
</script>
{% endblock %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}محصولات{% endblock %}
{% block body %}
  

<section class="products pt-8 md:pt-24 lg:pt-48 pb-20">

    <div class="container">

        <!-- Section Head -->
        <div class="flex justify-between items-end mb-5 md:mb-12">
            <div>
                <h3 class="section-title">جدید ترین محصولات</h3>
                <span class="section-subtitle">فراوری شده از دانه قهوه</span>
            </div>
            <a href="{% url 'products:products_list' %}" class="selection-link">
                <span class="hidden md:inline-block">مشاهده همه محصولات</span>
                <span class="inline-block md:hidden">مشاهده همه</span>
                <svg class="w-5 h-5">
                    <use href="#chevron-left"></use>
                </svg>
            </a>

        </div>

        <!-- Section Body -->
        <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3.5 md:gap-5 child:rounded-2xl mb-20">

            {% for product in products %}
            <div class="coffee-product p-2 md:p-5 bg-white dark:bg-zinc-700 shadow-normal"  data-product-id="{{ product.id }}">
           

                <div class="relative mb-2 md:mb-5">
                    <img src="{{ product.image.url }}" class="w-32 mx-auto md:w-auto" alt="product 3">
                </div>

                <h5
                    class="font-DanaMedium h-10 md:h-14 text-sm md:text-xl text-zinc-700 dark:text-white line-clamp-2">
                    <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h5>
                <div class="flex justify-between mt-1.5 md:mt-2.5 gap-x-2 md:gap-x-2.5">
                    <div class="text-teal-600 dark:text-emerald-500">
                        <span class="font-DanaDemiBold text-base md:text-xl">{{ product.price | intcomma:False }}</span>
                        <span class="text-xs md:text-sm tracking-tighter">تومان</span>
                 
                    </div>
             

                       

                            <span
                            class="add-to-cart flex-center w-[26px] h-[26px] md:w-9 md:h-9 rounded-full cursor-pointer text-gray-400 bg-gray-100 dark:bg-zinc-800 hover:text-white hover:bg-teal-600 dark:hover:bg-emerald-500 transition-all">
                            <svg class="w-4 h-4 md:w-[22px] md:h-[22px]">
                                <use href="#shopping-cart"></use>
                            </svg>
                        </span>
                        
            
            
                </div>


            </a>
      

        </div>
        {% endfor %}
    </div>

</section>

{% include 'pagination.html' %}

{% endblock %}

{% block script %}
<script>
     $(document).ready(function(){

    $('.add-to-cart').on('click', function(){
              addToCart($(this).closest('.coffee-product').data('product-id'));
          });
    
      
        function addToCart(itemId){
        $.ajax({
            type: 'POST',
            url: '{% url "cart:add_to_cart" %}',
            data: {
                'item_id': itemId,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function(data){
                $('.cart-count').text(data.item_count);
                cartBoxRefresh(data, {
                            cart_detail: "{% url 'cart:cart_detail' %}", 
                            order_create: "{% url 'orders:order_create' %}"});
            },
            fail: function(xhr, textStatus, errorThrown){
            alert('request failed');
    }
        });
    }
});



</script>
{% endblock script %}    